import type { Metadata } from "next";
import { Oxanium } from "next/font/google";
import "./globals.css";
import {NavBar, Footer} from './components/index'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const oxanium = Oxanium({
  variable: "--font-oxanium",
  subsets: ["latin"],
  weight: ["400", "600"], 
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <NavBar/>
      <body
        className={`${oxanium.variable} antialiased`}
      >
        {children}
      </body>
      <Footer/>
    </html>
  );
}
